version: "3.7"
services:
  db:
    image: mysql:5.7
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks: 
        - wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:5.9
    volumes:
      - plugin-data:/var/www/html/wp-content/plugins
      - ./:/var/www/html/wp-content/plugins/jpay-plugin
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
        - wordpress
volumes:
    data-mysql:
    plugin-data:

networks:
    wordpress: