version: "3.3"
services:
  db:
    image: mysql:5.7
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - "3306:3306"
    networks: 
        - wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:5.9
    container_name: wordpress
    volumes:
      - ./public:/var/www/html
      - plugin-data:/var/www/html/wp-content/plugins
      - ./:/var/www/html/wp-content/plugins/jpay-plugin
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 'true' 
      WORDPRESS_CONFIG_EXTRA: define('WP_ALLOW_MULTISITE', true );
    hostname: mainwordpress.com.local
    labels:
      com.plugin.expose.domain: "mainwordpress.com.local"
      com.plugin.expose.domainIsHost: "true"
    networks:
      - wordpress
volumes:
    data-mysql:
    plugin-data:

networks:
    wordpress: